// Code generated by Slice Machine. DO NOT EDIT.

import Member from "./Member/index.svelte";
import Members from "./Members/index.svelte";
import NamePf from "./NamePf/index.svelte";

export const components = {
  member: Member,
  members: Members,
  name_pf: NamePf,
};
