// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ProfilecardDocumentDataSlicesSlice = NamePfSlice;

/**
 * Content for profilecard documents
 */
interface ProfilecardDocumentData {
  /**
   * Slice Zone field in *profilecard*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: profilecard.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProfilecardDocumentDataSlicesSlice>
  /**
   * Meta Description field in *profilecard*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: profilecard.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *profilecard*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: profilecard.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *profilecard*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: profilecard.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * profilecard document from Prismic
 *
 * - **API ID**: `profilecard`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProfilecardDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProfilecardDocumentData>,
    "profilecard",
    Lang
  >;

export type AllDocumentTypes = ProfilecardDocument;

/**
 * Default variation for Member Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MemberSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Member*
 */
type MemberSliceVariation = MemberSliceDefault;

/**
 * Member Shared Slice
 *
 * - **API ID**: `member`
 * - **Description**: Member
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MemberSlice = prismic.SharedSlice<"member", MemberSliceVariation>;

/**
 * Default variation for Members Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MembersSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Members*
 */
type MembersSliceVariation = MembersSliceDefault;

/**
 * Members Shared Slice
 *
 * - **API ID**: `members`
 * - **Description**: Members
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MembersSlice = prismic.SharedSlice<
  "members",
  MembersSliceVariation
>;

/**
 * Primary content in *NamePf → Primary*
 */
export interface NamePfSliceDefaultPrimary {
  /**
   * Name field in *NamePf → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: name_pf.primary.name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * lastename field in *NamePf → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: name_pf.primary.lastename
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  lastename: prismic.RichTextField;

  /**
   * gamename field in *NamePf → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: name_pf.primary.gamename
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  gamename: prismic.RichTextField;

  /**
   * Timpf field in *NamePf → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: name_pf.primary.timpf
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  timpf: prismic.ImageField<never>;

  /**
   * about field in *NamePf → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: name_pf.primary.about
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  about: prismic.KeyTextField;
}

/**
 * Default variation for NamePf Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NamePfSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NamePfSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NamePf*
 */
type NamePfSliceVariation = NamePfSliceDefault;

/**
 * NamePf Shared Slice
 *
 * - **API ID**: `name_pf`
 * - **Description**: NamePf
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NamePfSlice = prismic.SharedSlice<"name_pf", NamePfSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ProfilecardDocument,
      ProfilecardDocumentData,
      ProfilecardDocumentDataSlicesSlice,
      AllDocumentTypes,
      MemberSlice,
      MemberSliceVariation,
      MemberSliceDefault,
      MembersSlice,
      MembersSliceVariation,
      MembersSliceDefault,
      NamePfSlice,
      NamePfSliceDefaultPrimary,
      NamePfSliceVariation,
      NamePfSliceDefault,
    };
  }
}
